### ISSUE TITLE
Can't build because missing beartime-core

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#1]

**Comment by kincaidoneil** [comment]
I have it working on my machine; I'll commit and push my changes by 7pm.
Thanks.

**Comment by mmccarthy717** [comment]
kincaid - came across this and it's really cool. are you in the msp area? would u be interested meeting up to discuss potentially working on a fun python / angular project?  regardless would love to meet and see what you are up to these days... shoot me a message at 612-223-3000

**Comment by kincaidoneil** [comment]
Fixed by 9e1318ecaed1d67ff606b033c1aaeb1844b10086
