### ISSUE TITLE
Don't show 'passing' text in countdown before first block of day

### ISSUE THREAD

**Issue by kincaidoneil** [Foo-Bear/beartime-web#14]

**Comment by 5aji** [comment]
On that note, nothing shows for monday/friday:
![screen shot 2016-09-09 at 08 20 25](https://cloud.githubusercontent.com/assets/9110284/18388209/5f6f2d58-7666-11e6-8a8c-e9e72ceffa45.png)

**Comment by kincaidoneil** [comment]
This is by design; Sean and I decided to display all the blocks entirely proportional, because if the countdown were displayed within the advisory block, Friday wouldn't use the same vertical space as Wednesday. There's still the countdown in the title of the tab, however.
