### ISSUE TITLE
Add about/created by text

### ISSUE THREAD

**Issue by kincaidoneil** [Foo-Bear/beartime-web#21]

**Comment by 5aji** [comment]
Just a small footer at the bottom should be fine.

**Comment by 5aji** [comment]
Without antialiasing
![screen shot 2016-09-09 at 07 58 00](https://cloud.githubusercontent.com/assets/9110284/18387613/29a5ef66-7663-11e6-99d4-79113e0e7847.png)

With antialiasing.
![screen shot 2016-09-09 at 08 01 48](https://cloud.githubusercontent.com/assets/9110284/18387700/bb81aede-7663-11e6-8cbd-9afec51d2c9f.png)

Preferences?

**Comment by shickey** [comment]
I do think it's important to credit those who worked on past versions. The list of names for BearStatus 1.0 is on that site and we should also credit Freddie Rice for creating the original BearTime for mac client

**Comment by 5aji** [comment]
Yup. Should we have a "credits" page, separate from the main website, with a full list of all contributors? I can put it on the github page for beartime-server.

**Comment by kincaidoneil** [comment]
@shickey I'm open to that, but how/where do you suppose we mention them?

**Comment by 5aji** [comment]
Maybe star wars style scroll page?

EDIT: we should also cite our dependencies.

**Comment by 5aji** [comment]
Missing deps, but #26 adds a credits page. Before I go convert it to HTML I would like your thoughts. Should I expand the section on OG beartime? I don't know much about it.

**Comment by 5aji** [comment]
I'll make some changes to the webpack to convert the CREDITS to an html page and put it in dist.

EDIT:
I have no idea how webpack works, so I'll just pass that one to you, @kincaidoneil
