### ISSUE TITLE
Characters get cut off

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#3]
![screen shot 2016-09-08 at 11 19 38](https://cloud.githubusercontent.com/assets/9110284/18357350/4d0c8de6-75b6-11e6-9806-74bc69902359.png)

**Comment by kincaidoneil** [comment]
What browser?

**Comment by 5aji** [comment]
Chrome Latest. Happens on Safari and Firefox as well.

**Comment by 5aji** [comment]
Also this.
![screen shot 2016-09-08 at 12 16 34](https://cloud.githubusercontent.com/assets/9110284/18359138/21ed2ffa-75be-11e6-8d27-f2ad21852ec3.png)
I should add this is a low priority bug, so we should only take it up when we're sure it is stable.

**Comment by kincaidoneil** [comment]
Could you give me some steps to reproduce?

I'm not experiencing it.

![image](https://cloud.githubusercontent.com/assets/6435238/18360827/33a6b502-75c5-11e6-8b97-d3f8f91f0255.png)

**Comment by kincaidoneil** [comment]
Fixed by 3977c951d083ecdbced2abbdd188124ea98a9ec8.
