### ISSUE TITLE
UI for Free Blocks?

### ISSUE THREAD

**Issue by shickey** [Foo-Bear/beartime-web#36]
Just a random thought I had: would it be useful to have some custom UI for free blocks? E.g., if I have block 4 free, maybe I can indicate that somehow and then that UI element becomes transparent into the background? Here's a mockup:

![screen shot 2016-09-14 at 8 50 41 am](https://cloud.githubusercontent.com/assets/1489558/18514761/72a71e12-7a58-11e6-8c50-ed6a2f96ddfc.png)

**Comment by shickey** [comment]
Or more extreme:

![screen shot 2016-09-14 at 8 52 56 am](https://cloud.githubusercontent.com/assets/1489558/18514826/a968b73a-7a58-11e6-8bc4-0a23bbebdbba.png)

**Comment by 5aji** [comment]
I'm thinking of adding a little settings modal to each class where you could do this and also set it to be unique...

**Comment by kincaidoneil** [comment]
As long as we find a way to do it that maintains simplicity _and_ ease of
use, I'm game.

**Comment by kincaidoneil** [comment]
@shickey's idea: on page load, show all the UI blocks, but then if any are labeled “free”, they fade out after 10 or so seconds, giving the user time to click on it and change it if they want

**Comment by kincaidoneil** [comment]
Added in 2474bf7.
