### ISSUE TITLE
Better solution to modifying API requests in dev and production?

### ISSUE THREAD

**Issue by kincaidoneil** [Foo-Bear/beartime-web#43]
Right now, whenever I pull I have to manually change the frontend API url to `localhost:3000/api/week` from `/api/week`. I'm musing, would it be feasible to run the webpack dev server through the existing backend? There's a way to integrate it, and that way, it wouldn't require any changes--that'd be run in unison.

I may not be explaining this clearly enough but it's just an idea

**Comment by 5aji** [comment]
Maybe [this?](http://madole.github.io/blog/2015/08/26/setting-up-webpack-dev-middleware-in-your-express-application/)

**Comment by kincaidoneil** [comment]
Moving to Firebase obviates this, but using webpack-dev-server's proxy feature would solve it anyways.
