### ISSUE TITLE
Better column support

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#54]
Right now, after a certain point, the app renders one column. However, there is so much extra room, so it could render 3. Instead of squishing columns until a certain point, it should squish and then remove one column and repeat until there is one left.

**Comment by 5aji** [comment]
![screen shot 2017-02-22 at 10 57 23](https://cloud.githubusercontent.com/assets/9110284/23222515/be0fe456-f8ed-11e6-9651-5f49e6e43368.png)

**Comment by kincaidoneil** [comment]
I don't think it provides enough utility to warrant the extra code. It'd also kinda complicate the user experience. Maybe just make the minimum size for week view smaller? Say 900 or 1000px? What do you think? It's 1100 in the current build.
