### ISSUE TITLE
Create a consistent icon and favicon

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#8]

**Comment by kincaidoneil** [comment]
![optimised](https://cloud.githubusercontent.com/assets/6435238/18415460/0b79164c-77b9-11e6-8b3a-7301837945bb.png)

Just an idea. Thoughts? (slightly modified from http://www.flaticon.com/free-icon/bear_141734#term=bear&page=1&position=23)

**Comment by kincaidoneil** [comment]
Added in d8dccdd.
